version: "3"

services:

  api:
    build: ../
    command: uvicorn twitter.entrypoints.fastapi_app:app --port 8000 --reload --host 0.0.0.0
    ports:
      - 8000:8000
    depends_on:
      - db
      - celery
    environment:
      - BROKER_HOST=rmq
    env_file: ../.env
    volumes:
      - ..:/code
      - type: bind
        source: ../.env
        target: /envfile/.env
  celery:
    build: ../
    command: celery -A twitter.entrypoints.celery_app:celery worker
    depends_on:
      - rmq
    environment:
      - BROKER_HOST=rmq
    env_file: ../.env
    volumes:
      - ..:/code
      - type: bind
        source: ../.env
        target: /envfile/.env
  celery_flower:
    build: .
    command: celery -A twitter.entrypoints.celery_app:celery flower
    volumes:
      - ..:/code
    ports:
      - 5555:5555
    depends_on:
      - rmq
    environment:
      - BROKER_HOST=rmq
  db:
    image: postgres:15
    ports:
      - 8080:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  rmq:
    image: rabbitmq

volumes:
  postgres_data:
